-- ============================================
-- PORTFOLIO CMS - DATABASE SEEDERS
-- ============================================
-- Version: 1.0.0
-- Created: 2025-01-13
-- Description: Initial data seeding from existing HTML
-- ============================================

-- Clear existing data
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE testimonials;
TRUNCATE TABLE contact_info;
TRUNCATE TABLE services;
TRUNCATE TABLE portfolio;
TRUNCATE TABLE education;
TRUNCATE TABLE experience;
TRUNCATE TABLE skills;
TRUNCATE TABLE about;
TRUNCATE TABLE admin_users;
SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- SEED: admin_users
-- ============================================
-- Password: Khalidprofile321.
-- Hash will be generated by run-migrations.php
-- If importing manually, generate hash first with generate-password.php
-- Temporary hash (CHANGE THIS!):
TRUNCATE TABLE admin_users;
INSERT INTO admin_users (username, password, email, full_name, is_active) VALUES 
('admin_khalid', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'holitsky98@gmail.com', 'Khalid Saifullah', TRUE);

-- ============================================
-- SEED: about
-- ============================================
TRUNCATE TABLE about;
INSERT INTO about (title, description, video_background) VALUES 
('About me', 
'Hello! I am Khalid, a Web Developer with a deep passion for technology and software development. My journey in tech has led me to specialize in creating dynamic and scalable web applications, with a strong foundation in JavaScript and PHP. I have extensive experience working with frameworks such as Laravel, CodeIgniter, and React, allowing me to develop high-performance, maintainable, and user-centric applications. I am committed to improving my skills and exploring new technologies to create innovative and impactful solutions.

I am someone who is always eager to learn new things. In addition to my interest in web application development, I also have a passion for various fields of technology, such as mobile application development and Geographic Information Systems (GIS). Moreover, I have a strong interest in UI/UX design, as I believe that an intuitive and well-crafted interface plays a crucial role in enhancing user experience and ensuring an application''s success. I am confident that by continuously expanding my knowledge in different areas of technology, I can become a more creative developer.',
'./assets/images/video/video4.mp4');

-- ============================================
-- SEED: contact_info
-- ============================================
TRUNCATE TABLE contact_info;
INSERT INTO contact_info (email, phone, birthday, location, linkedin, instagram) VALUES 
('holitsky98@gmail.com', 
'+62 821-4768-8858', 
'1998-07-15', 
'South Tangerang, West Java, Indonesia',
'https://www.linkedin.com/in/khalid-saifullah-a90a05217/',
'https://www.instagram.com/holit_sky/');

-- ============================================
-- SEED: services
-- ============================================
TRUNCATE TABLE services;
INSERT INTO services (title, description, icon, sort_order) VALUES 
('Web development (CodeIgniter & Laravel)', 
'A developer who has built various web applications (both individually and collaboratively)', 
'icon-dev.svg', 
1),

('UI/UX Design (Figma)', 
'Experienced in designing UI/UX for web and mobile applications using Figma (both individually and collaboratively)', 
'icon-design.svg', 
2),

('Mobile software development (React Native)', 
'Developed mobile applications using React Native', 
'icon-app.svg', 
3);

-- ============================================
-- SEED: skills (Technologies I Work With)
-- ============================================
TRUNCATE TABLE skills;
INSERT INTO skills (name, icon, sort_order) VALUES 
('HTML', './assets/images/icon/html-icon.svg', 1),
('CSS', './assets/images/icon/css-icon.svg', 2),
('Javascript', './assets/images/icon/js-icon.svg', 3),
('Bootstrap', './assets/images/icon/bootstrap-icon.svg', 4),
('PHP', './assets/images/icon/php-icon.svg', 5),
('CodeIgniter', './assets/images/icon/ci-icon.svg', 6),
('Laravel', './assets/images/icon/laravel-icon.svg', 7),
('React', './assets/images/icon/icon-react.svg', 8),
('MySQL', './assets/images/icon/mysql-icon.svg', 9),
('GIT', './assets/images/icon/icon-git.svg', 10),
('Postman', './assets/images/icon/postman-icon.svg', 11),
('Figma', './assets/images/icon/figma-icon.svg', 12);

-- ============================================
-- SEED: education
-- ============================================
TRUNCATE TABLE education;
INSERT INTO education (degree, institution, location, start_date, end_date, description, gpa, sort_order) VALUES 
('Informatics Engineering / Teknik Informatika', 
'Universitas Ibn Khaldun Bogor', 
'Bogor, Indonesia',
'2019-09-01', 
'2024-08-31', 
'GPA: 3.53, Concentration: Software Engineering
Developed the SIJAB mobile application as a final project, designed to provide real-time information by displaying CCTV footage to monitor road and transportation conditions in Bogor City. The application delivers data on traffic density, public facility locations, routes, and the latest traffic news in Bogor City.
Completed the MBKM program at Bappedalitbang Bogor Regency by designing and developing the UI/UX for a web application to ensure its interface and functionality align with client needs and preferences.',
'3.53',
1);

-- ============================================
-- SEED: experience
-- ============================================
TRUNCATE TABLE experience;
INSERT INTO experience (title, company, location, start_date, end_date, is_current, description, technologies, sort_order) VALUES 

-- Current Position
('Technical Assistant – GIS Programming', 
'Ministry of Forestry – M4CR Project', 
'Jakarta, Indonesia',
'2025-05-01', 
NULL, 
TRUE,
'Contracted as a technical assistant to provide specialized support in geospatial information system (GIS) programming and network management for the Joint Information Geospatial (JIG) Team under the Ministry of Forestry, specifically supporting the Walidata Geospatial unit of the Directorate of IPSDH.
Provided technical guidance and operational support to the Walidata Geospatial team (Directorate of IPSDH) and Geospatial Data Producers in managing geospatial information networks, including both hardware and software environments.
Supported the integration processes between the SIGAP Information System and systems developed under the M4CR Project, as well as previously integrated supporting systems within the scope of the Walidata Geospatial mandate.
Assisted in diagnosing, troubleshooting, and resolving technical issues related to geospatial network management, GIS programming, and spatial database operations.
Contributed to the management and maintenance of the Ministry''s forestry geospatial information network to ensure efficient, effective, and optimized system performance for M4CR Project Sub-Component.
Prepared reports documenting technical incidents, challenges, and provided solution recommendations throughout the contract period, covering both spatial database management and geospatial information network operations.',
'GIS, Spatial Database, Network Management, PostgreSQL, ArcGIS',
1),

-- Previous Positions
('Web Developer & IT Consultant', 
'Badan Standardisasi Instrumen Lingkungan Hidup dan Kehutanan (BSILHK)', 
'Jakarta, Indonesia',
'2024-08-01', 
'2024-12-31',
FALSE,
'Contracted as an independent IT consultant and web developer to provide technical expertise and system development services for BSILHK''s digital infrastructure initiatives.
Implemented the MVC (Model-View-Controller) architecture in Laravel and CodeIgniter 3 for structured system development.
Developed interactive mapping features using Leaflet.js for visualization and monitoring of entity and laboratory distributions across Indonesia.
Performed maintenance and bug fixing for the LiNE BSILHK information system to ensure smooth system operation, as well as updates and enhancements for specific features required as part of the advanced development stage of the LiNE BSILHK information system.',
'Laravel, CodeIgniter 3, Leaflet.js, MySQL, MVC Architecture',
2),

('Web Developer & UI/UX Designer', 
'Arculus Indonesia', 
'Jakarta, Indonesia',
'2022-08-01', 
'2024-10-31',
FALSE,
'Developed multiple website projects for government clients including Korlantas Polri, Arculus Web, VOCA, and Hadiwana using CodeIgniter 3 and Laravel frameworks.
Designed comprehensive UI/UX solutions including dashboard interfaces, wireframes, mockups, and prototypes using Figma.
Created user-centered designs for SINADI DKI website dashboard and conducted user research to understand client needs and preferences.
Collaborated with Dinas PUPR DKI Jakarta as UI/UX designer, delivering intuitive design solutions based on usability testing and user feedback.
Implemented dynamic data integration and Content Management System (CMS) for seamless content management.
Managed data architecture using MySQL database to ensure efficient data storage and retrieval.
Actively participated in cross-functional team collaboration, sharing insights between development and design processes.',
'CodeIgniter 3, Laravel, Figma, MySQL, UI/UX Design, CMS Development',
3),

('Data Entry Operator', 
'K3I Korlantas Polri', 
'Jakarta, Indonesia',
'2022-10-01', 
'2022-11-30',
FALSE,
'Serving as an operator to monitor a system tracking the movements of on-site personnel.
Inputting data of officers who will escort international guests involved in the G20 summit.
Enhancing data management and organizational skills.',
'Data Entry, System Monitoring, Data Management',
4);

-- ============================================
-- SEED: portfolio (Match static HTML order)
-- ============================================
TRUNCATE TABLE portfolio;
INSERT INTO portfolio (title, category, description, image, image_webp, demo_url, github_url, technologies, featured, sort_order) VALUES 

-- Web Development Projects (sort_order 1-9)
('Radar Kemenlh', 
'Web Development', 
'Ministry of Environment and Forestry radar monitoring system.',
'./assets/images/radar-web.png',
'./assets/images/optimized/radar-web.webp',
'https://radar.kemenlh.go.id/',
NULL,
'Laravel, MySQL, Real-time Monitoring',
TRUE,
1),

('Sigap Award', 
'Web Development', 
'Award management system for SIGAP program.',
'./assets/images/sigap-award.png',
'./assets/images/optimized/sigap-award.webp',
'https://sigap-award.site/',
NULL,
'Laravel, MySQL, Award System',
TRUE,
2),

('Ownskin Website', 
'Web Development', 
'E-commerce website for Ownskin beauty products.',
'./assets/images/ownskin-web.png',
'./assets/images/optimized/ownskin-web.webp',
'https://ownskin.co.id/',
NULL,
'Frontend Development, E-commerce',
FALSE,
3),

('E-Learning Kementerian Lingkungan Hidup', 
'Web Development', 
'Learning management system for Ministry of Environment and Forestry.',
'./assets/images/lms-klh.png',
'./assets/images/optimized/lms-klh.webp',
'https://elearning.kemenlh.go.id/',
NULL,
'Laravel, LMS, E-Learning',
FALSE,
4),

('LINE BSILHK - Badan Standardisasi Instrumen Lingkungan Hidup dan Kehutanan', 
'Web Development', 
'Environmental and Forestry Standardization Laboratory Information System.',
'./assets/images/line-web.png',
'./assets/images/optimized/line-web.webp',
'https://line.bsilhk.menlhk.go.id/',
NULL,
'CodeIgniter, Laravel, Leaflet.js, MySQL',
TRUE,
5),

('Hadiwana Tirta Lestari', 
'Web Development', 
'Corporate website for Hadiwana water conservation organization.',
'./assets/images/hadiwana-web.png',
'./assets/images/optimized/hadiwana-web.webp',
'https://hadiwanatales.org/',
NULL,
'Laravel, Corporate Website',
FALSE,
6),

('K3i Korlantas Polri', 
'Web Development', 
'Traffic police information system for Indonesian National Police.',
'./assets/images/k3i-web.png',
'./assets/images/optimized/k3i-web.webp',
'https://web.k3i-korlantas.id/login',
NULL,
'CodeIgniter, Police System',
FALSE,
7),

('Voca', 
'Web Development', 
'Web platform for Arculus Indonesia client.',
'./assets/images/voca-web.png',
'./assets/images/optimized/voca-web.webp',
'https://voca.arculus-indonesia.com/',
NULL,
'CodeIgniter, CMS',
FALSE,
8),

('Trident', 
'Web Development', 
'Financial platform for Arculus Indonesia.',
'./assets/images/trident-web.png',
'./assets/images/optimized/trident-web.webp',
'https://trident.arculus-indonesia.com/home',
NULL,
'CodeIgniter, Finance System',
FALSE,
9),

-- UI UX Design Projects (sort_order 10-11, displayed at bottom)
('SINADI DKI Dashboard', 
'UI UX Design', 
'Dashboard design for Jakarta Public Works Department infrastructure monitoring.',
'./assets/images/sinadi.png',
'./assets/images/optimized/sinadi.webp',
'https://www.figma.com/proto/wyuIrVAzOYBNpno44w1kWg/SINADI---DKI?page-id=758%3A1&node-id=3220-8460&node-type=frame&viewport=-1300%2C-1426%2C0.35&t=yE5xG5cemOHIjqvG-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=3220%3A8460',
NULL,
'Figma, UI UX Design, Dashboard',
TRUE,
10),

('Inovator', 
'UI UX Design', 
'Innovation management platform UI UX design.',
'./assets/images/inovator.png',
'./assets/images/optimized/inovator.webp',
'https://www.figma.com/proto/z2cmiFBWWHhMgMLfMFSmpL/WEB-INOVATOR?page-id=1%3A18&node-id=363-1059&viewport=15975%2C-3689%2C1.31&t=Gm1RP3SeRsfQRmLa-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=363%3A1059&show-proto-sidebar=1',
NULL,
'Figma, UI UX Design',
FALSE,
11),

-- Mobile Development (sort_order 12, displayed at bottom)
('SIJAB Mobile Application', 
'Mobile Development', 
'Real-time traffic monitoring mobile app for Bogor City with CCTV integration.',
'./assets/images/sijab-mobile.png',
'./assets/images/optimized/sijab-mobile.webp',
NULL,
NULL,
'React Native, GIS, Real-time Data',
TRUE,
12);

-- ============================================
-- SEED: testimonials (Sample)
-- ============================================
TRUNCATE TABLE testimonials;
INSERT INTO testimonials (name, position, company, content, rating, is_active, sort_order) VALUES 

('John Doe', 
'Project Manager', 
'Arculus Indonesia',
'Khalid is an exceptional developer with strong technical skills in both frontend and backend development. His UI/UX design expertise adds great value to our projects.',
5,
TRUE,
1),

('Jane Smith', 
'Senior Developer', 
'BSILHK',
'Working with Khalid was a great experience. He delivered high-quality code and was always willing to help the team. His knowledge of Laravel and GIS integration is impressive.',
5,
TRUE,
2);

-- ============================================
-- SEEDING COMPLETE
-- ============================================

-- Verify data
SELECT 'Admin Users' as 'Table', COUNT(*) as 'Records' FROM admin_users
UNION ALL
SELECT 'About', COUNT(*) FROM about
UNION ALL
SELECT 'Contact Info', COUNT(*) FROM contact_info
UNION ALL
SELECT 'Services', COUNT(*) FROM services
UNION ALL
SELECT 'Skills', COUNT(*) FROM skills
UNION ALL
SELECT 'Education', COUNT(*) FROM education
UNION ALL
SELECT 'Experience', COUNT(*) FROM experience
UNION ALL
SELECT 'Portfolio', COUNT(*) FROM portfolio
UNION ALL
SELECT 'Testimonials', COUNT(*) FROM testimonials;
